ERROR:task_2:Ошибка division by zero в функции func_2 при аргументах (5, 0), {}
ERROR:task_2:Ошибка 'a' в функции my_func при аргументах ({'f': '1', 'd': '3', 's': '5'}, 'a', 23), {}
