
============================================ ERRORS =============================================
__________________________________ ERROR collecting test_1.py ___________________________________
.folder\Lib\site-packages\_pytest\runner.py:341: in from_call
    result: Optional[TResult] = func()
.folder\Lib\site-packages\_pytest\runner.py:372: in <lambda>
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
.folder\Lib\site-packages\_pytest\python.py:531: in collect
    self._inject_setup_module_fixture()
.folder\Lib\site-packages\_pytest\python.py:545: in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
.folder\Lib\site-packages\_pytest\python.py:310: in obj
    self._obj = obj = self._getobj()
.folder\Lib\site-packages\_pytest\python.py:528: in _getobj
    return self._importtestmodule()
.folder\Lib\site-packages\_pytest\python.py:617: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
.folder\Lib\site-packages\_pytest\pathlib.py:567: in import_path
    importlib.import_module(module_name)
C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1206: in _gcd_import
    ???
<frozen importlib._bootstrap>:1178: in _find_and_load
    ???
<frozen importlib._bootstrap>:1149: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:690: in _load_unlocked
    ???
.folder\Lib\site-packages\_pytest\assertion\rewrite.py:186: in exec_module
    exec(co, module.__dict__)
test_1.py:112: in <module>
    print(line)
E   OSError: [WinError 6] Неверный дескриптор
==================================== short test summary info ====================================
ERROR test_1.py - OSError: [WinError 6] Неверный дескриптор
!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
1 error in 0.70s
